const db = require("./connection/database")
const category_fun = require("./functions/category_fun")
const author_fun = require("./functions/author_fun")
const {Sequelize} = require('sequelize')
// let Category = require("./models/category")
// Category.sync( alter = true)
// let Author = require("./models/authors")
// Author.sync()
// let Book = require("./models/book")
// Book.sync()
// category_fun.destroy({name:"action"})
const A = Sequelize.define("authors")
const B = Sequelize.define("book")
A.belongsToMany(B)